### ISSUE TITLE
DSL Definitivo (o quasi)

### ISSUE THREAD

**Issue by pfazzi** [phparkitect/arkitect#45]
Allego qui il DSL emerso dalla call odierna:
```php
Rule::classes()  // alternative non mutuamente esclusive papabili: allItems, allTraits, allClasses, allInterfaces, allMethods
    ->that(new Expression\ResideInControllerNamespace())
        ->andThat(Exp::qualcosa()) // sisntassi alternativa per la creazione di espressioni che evita la keyword new
    ->should(new Expression\HaveNameEndingWith('Controller'))
    ->because('Controllers should have name ending with proper suffix')
;
```
## todo

 - [x] passare argomenti a that e should #47
 - [x] usare Expression al posto di spec e costraint #48 
 - [ ] convertire i vecchi spec in Expression, aggiornando l'interfaccia per renderla coerente. #56 
 - [ ] permettere un solo should per non gestire AND OR o condizione strane per questa prima fase. #57 

cc @AlessandroMinoccheri
